name: Release Drafter
tag-template: v$NEW_VERSION
categories:
  - title: '🚀 Features'
    labels: ['feature']
  - title: '🐛 Bug Fixes'
    labels: ['bug']
  - title: '🛠 Maintenance'
    labels: ['chore', 'refactor']
change-template: '- ${{PR.title}} (#${{PR.number}}) by @${{PR.author}}'
template: |
  ## What's Changed
  $CHANGES
