name-template: 'Release ${{ version }}'
tag-template: '${{ version }}'
categories:
  - title: 'New Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Performance Improvements'
    label: 'performance'
  - title: 'Refactorings'
    label: 'refactor'
change-template: '- [PR #${{ number }}] ${{ title }} (thanks to @${{ author }})'
template: |
  Changes in this release:
  $CHANGES
no-changes-template: '* No changes'

no-contributors-template: No contributors

category-template: '## $TITLE'
