name-template: 'Release ${{ version }}'
tag-template: '${{ version }}'
categories:
  - title: 'New Features'
    labels: ['feature']
  - title: 'Bug Fixes'
    labels: ['bug']
  - title: 'Documentation'
    labels: ['documentation']
  - title: 'Performance Improvements'
    labels: ['performance']
  - title: 'Refactorings'
    labels: ['refactor']

change-template: '- [PR #${{ number }}] ${{ title }} (thanks to @${{ author }})'
template: |
  ## Changes in this Release
  $CHANGES

no-changes-template: '* No changes'

category-template: '### $TITLE'
