name: Sync Labels

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.json'
  workflow_dispatch:

jobs:
  sync_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure repository labels
        run: |
          echo "::group::Reading labels JSON file"
          labels=$(cat .github/labels.json)
          echo "Labels: $labels"
          echo "::endgroup::"
          
          echo $labels | jq -c '.[]' | while read label; do
            name=$(echo $label | jq -r '.name')
            color=$(echo $label | jq -r '.color' | tr -d '#')
            description=$(echo $label | jq -r '.description')
          
            echo "Updating label: $name with color #$color and description '$description'"
          
            # Update the labels using the create-or-update-label action
            gh label create "$name" --color "$color" --description "$description" || gh label edit "$name" --color "$color" --description "$description"
          
          done
