name: Update Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_draft_release:
    permissions:
      contents: write
      pull-requests: write
    name: Update Draft Release
    runs-on: ubuntu-latest

    steps:
      - name: Auto-generate Draft Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
