name: Update Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  update_draft_release:
    name: Update Draft Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub Actions settings
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Auto-generate Release Notes
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
